# Generated by Django 3.1.1 on 2020-10-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.CharField(blank=True, choices=[('GD', 'Gadget'), ('SP', 'Sport')], max_length=200, null=True),
        ),
    ]
