# Generated by Django 3.1.1 on 2020-10-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201004_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('GD', 'Gadget'), ('SP', 'Sport')], max_length=200),
        ),
    ]
